app:
  title: Backstage (Sandbox)
  baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io

backend:
  baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io

  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: shared
  providers:
    github:
      shared:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
