app:
  title: Backstage (Sandbox)
  baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io

backend:
  baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io
  listen: ':7007'

  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  providers:
    gcpIap:
      audience:
        project: 362793201562
        backendService: 3529575844611151066
      jwtHeader:
        name: x-goog-iap-jwt-assertion
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail

  permissions:
    rules:
      - name: backstage-admin-rule
        resourceType: all
        policy: allow
        conditions:
          - type: group
            group: admins

catalog:
  locations:
    - type: file
      target: ./examples/admin.yaml
      rules:
        - allow: [User, Group]
