backstage:
  image:
    repository: backstage

  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
      args:
        - "--private-ip"
        - "--port=5432"
      securityContext:
        runAsNonRoot: true
      resources:
        limits:
          memory: "1Gi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: 10m
