backstage:
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
      args:
        - --private-ip
        - --port=5432
      securityContext:
        runAsNonRoot: true
      resources:
        limits:
          memory: 1Gi
          cpu: 100m
        requests:
          memory: 128Mi
          cpu: 10m

  extraEnvVarsSecrets:
    - github-app-credentials
    - postgres-secrets

  image:
    repository: backstage

  podLabels:
    tags.datadoghq.com/service: backstage

  appConfig:
    app:
      title: Backstage (Sandbox)
      baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io

    organization:
      name: Open Source Infrastructure (as Code)

    backend:
      baseUrl: https://backstage-us-east1.sb.gcp.osinfra.io

      # Content-Security-Policy that allows the backend to load GitHub avatars as part of the
      # GitHub Organizational Data plugin.
      csp:
        connect-src: ["'self'", "http:", "https:"]
        img-src: ["'self'", "data:", "https://avatars.githubusercontent.com"]

      database:
        client: pg
        connection:
          host: localhost
          port: 5432
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}

    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              privateKey: ${GITHUB_APP_PRIVATE_KEY}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}

    techdocs:
      builder: "local"
      generator:
        runIn: "docker"
      publisher:
        type: "local"

    auth:
      providers:
        gcpIap:
          # You can find the backend service ID using the following command:
          # gcloud compute backend-services list --format="table(name, id)"
          audience: /projects/362793201562/global/backendServices/1248042603684159396

    catalog:
      providers:
        githubOrg:
          id: github
          githubUrl: https://github.com
          orgs: [osinfra-io]
          schedule:
            initialDelay: { seconds: 30 }
            frequency: { hours: 24 }
            timeout: { minutes: 50 }

    permission:
      enabled: true

service:
  annotations:
    cloud.google.com/backend-config: '{"default": "backstage-backend"}'
  type: NodePort

serviceAccount:
  name: backstage-workload-identity-sa
