# This is based on the Backstage deployment guide:
# https://backstage.io/docs/deployment/docker

name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    paths:
      - global/app/backstage/**
    branches:
      - main
  pull_request:
    paths:
      - global/app/backstage/**

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker-image:
    name: Build and push to GitHub Container Registry
    if: github.actor != 'dependabot[bot]' && github.actor != 'osinfra-sa'
    runs-on: ubuntu-latest
    env:
      # The release version of Backstage plus our own versioning
      VERSION: v1.21.1-01

    steps:
      # Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout code
        uses: actions/checkout@v4.1.1

      # Setup Node
      # https://github.com/marketplace/actions/setup-node-js-environment

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          cache: yarn
          cache-dependency-path: global/app/backstage/yarn.lock
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Yarn install
        working-directory: global/app/backstage
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn tsc
          yarn build:backend --config ../../app-config.yaml

      # Docker Buildx
      # https://github.com/marketplace/actions/docker-setup-buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Docker Login
      # https://github.com/marketplace/actions/docker-login

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker images
      # https://github.com/marketplace/actions/build-and-push-docker-images

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: './global/app/backstage'
          file: ./global/app/backstage/packages/backend/Dockerfile
          cache-from: |
            ${{ github.event_name == 'pull_request' && 'type=gha' || '' }}
            ${{ github.event_name == 'push' && 'type=registry,ref=ghcr.io/osinfra-io/backstage:latest' || '' }}
          cache-to: |
            ${{ github.event_name == 'pull_request' && 'type=gha,mode=max' || '' }}
            ${{ github.event_name == 'push' && 'type=inline' || '' }}
          push: true
          tags: |
            ${{ github.event_name == 'pull_request' && format('ghcr.io/osinfra-io/backstage:{0}', github.sha) || '' }}
            ${{ github.event_name == 'push' && format('ghcr.io/osinfra-io/backstage:{0}', env.VERSION) || '' }}
            ${{ github.event_name == 'push' && 'ghcr.io/osinfra-io/backstage:latest' || '' }}
