name: Sandbox Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  us_east1_b:
    name: "Sandbox Regional: us-east1-b"
    uses: osinfra-io/github-opentofu-gcp-called-workflows/.github/workflows/plan-and-apply.yml@367d86eecaab18bb7fae7f5fa17fe7001df13f16 # v0.2.7
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox: Regional - us-east1-b"
      service_account: plt-backstage-github@plt-lz-backend-tf69-sb.iam.gserviceaccount.com
      opentofu_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars -var=backstage_version=${{ github.sha }}
      opentofu_state_bucket: plt-backstage-0bf7-sb
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: us-east1-b-sandbox
      working_directory: deployments/regional
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      opentofu_plan_secret_args: >-
        -var=datadog_api_key=${{ secrets.DATADOG_API_KEY }}
        -var=datadog_app_key=${{ secrets.DATADOG_APP_KEY }}
        -var=github_app_client_secret=${{ secrets.APP_CLIENT_SECRET }}
        -var=github_app_private_key=${{ secrets.APP_PRIVATE_KEY }}
        -var=github_app_webhook_secret=${{ secrets.APP_WEBHOOK_SECRET }}
        -var=github_auth_client_secret=${{ secrets.AUTH_CLIENT_SECRET }}
