name: Sandbox Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  us_east1_b:
    name: "Sandbox Regional: us-east1-b"
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.6
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east1-b-sandbox
      github_environment: "Sandbox: Regional - us-east1-b"
      service_account: plt-backstage-github@plt-lz-terraform-tf00-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars -var=backstage_version=${{ github.sha }}
      terraform_state_bucket: plt-backstage-4312-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east1-b-sandbox
      working_directory: deployments/regional
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: >-
        -var=datadog_api_key=${{ secrets.DATADOG_API_KEY }}
        -var=datadog_app_key=${{ secrets.DATADOG_APP_KEY }}
        -var=github_app_client_secret=${{ secrets.APP_CLIENT_SECRET }}
        -var=github_app_private_key=${{ secrets.APP_PRIVATE_KEY }}
        -var=github_app_webhook_secret=${{ secrets.APP_WEBHOOK_SECRET }}
